spring:
  cloud:
    nacos:
      server-addr: 192.168.147.132:8848
    gateway:
      routes:
        # 路由到商品服务
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        # 路由到会员服务
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 路由到仓库服务
        - id: warehouse-route
          uri: lb://mall-warehouse
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        # 路由到第三方服务
        - id: third-party-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        # 路由到后台管理服务
        - id: admin_route
          uri: lb://mall-admin
          # 有API前缀先默认路由到mall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /mall-admin/$\{segment}

  application:
    name: mall-gateway
server:
  port: 88
