spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.147.132:3306/mall_product?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # \u914D\u7F6E\u4E3B\u952E\u81EA\u589E
  global-config:
    db-config:
      id-type: auto
